name: sentinel1_decode
channels:
  - conda-forge
dependencies:
  - cmake
  - ninja
  - openmp
  - cxx-compiler  # or clang_osx-64 on macOS
  - fftw
  - libtiff
  - opencv
  - pkg-config
  - python=3.11
