# toolchain-conda.cmake
set(CMAKE_PREFIX_PATH "$ENV{CONDA_PREFIX}" CACHE PATH "Conda install path" FORCE)
set(CMAKE_FIND_ROOT_PATH "$ENV{CONDA_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
